remote_theme: just-the-docs/just-the-docs@v0.5.3
plugins:
- jekyll-remote-theme
title: Informatika
description: Vzdelávacie materiály pre predmet Informatika
show_downloads: false
compress_html:
  blanklines: true
latex: katex
